version: '3.1'

services:
  api:
    build: .
    ports:
      - "80:8080"
    environment:
      PG_HOST: pg-database
      PG_PORT: "5432"
      PG_USER: worker
      PG_PASSWORD: example
      PG_DB_NAME: recordings
    restart: on-failure
    depends_on:
      - pg-database
    links:
      - pg-database
    secrets:
      - db_secrets

  pg-database:
    image: postgres:16
    restart: always
    container_name: pg-database
    hostname: pg-database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secrets
      POSTGRES_USER: worker
    volumes:
      - 03-go-db:/var/lib/postgresql/data
      - ./:/init-table
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    secrets:
      - db_secrets

volumes:
  03-go-db:

secrets:
  db_secrets:
    file: ./secrets/db-pass-secret
